def main():
    print("Hello World from Mojo!")
    print("Bonjour tout le monde!")
    print("Hallo Wereld!")
    print("¡Hola, mundo!")
    print("Καλημέρα κόσμε!")
    print("你好")
    print("こんにちは 世界!")
    print("ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ")
    print("👋🌍❗")
